function(get_interface_path IName IPath)
  string(FIND ${IName} ":" DELIMITER_INDEX)
  string(SUBSTRING ${IName} 0 ${DELIMITER_INDEX} INTERFACE_NAME)
  string(REPLACE "." "/" INTERFACE_PATH ${INTERFACE_NAME})
  set(${IPath} ${INTERFACE_PATH} PARENT_SCOPE)
endfunction(get_interface_path)

function(get_interface_file IName IFile)
  string(FIND ${IName} ":" DELIMITER_INDEX)
  string(SUBSTRING ${IName} 0 ${DELIMITER_INDEX} INTERFACE_NAME)
  string(FIND ${INTERFACE_NAME} "." FDEPL_INDEX REVERSE)
  math(EXPR FILE_INDEX ${FDEPL_INDEX}+1)
  string(SUBSTRING ${INTERFACE_NAME} ${FILE_INDEX} -1 FILE_NAME)
  set(${IFile} ${FILE_NAME} PARENT_SCOPE)
endfunction(get_interface_file)

function(get_interface_version IName IVersion)
  string(FIND ${IName} ":" DELIMITER_INDEX)
  math(EXPR VERSION_INDEX ${DELIMITER_INDEX}+1)
  string(SUBSTRING ${IName} ${VERSION_INDEX} -1 INTERFACE_VERSION)
  set(${IVersion} ${INTERFACE_VERSION} PARENT_SCOPE)
endfunction(get_interface_version)